# Generated by Django 4.1 on 2022-09-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_businessdeal_currency_businessdeal_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdeal',
            name='unique_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessstore',
            name='unique_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
