# Generated by Django 4.1 on 2022-09-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_businessdeal_unique_title_businessstore_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
