# Generated by Django 4.1 on 2022-09-27 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_businessstore_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.currency'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Arabic', 'Arabic')], default='English', max_length=255, null=True),
        ),
    ]
