# Generated by Django 4.1 on 2022-09-27 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_user_currency_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_officer_name', models.CharField(blank=True, max_length=228, null=True)),
                ('account_officer_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=32, null=True)),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to='Business_logo/AccountOfficer/%Y/%m')),
                ('business_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.businessstore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accountofficer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
