# Generated by Django 4.1 on 2022-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_account_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_account_officer',
            field=models.BooleanField(default=False),
        ),
    ]
