# Generated by Django 4.1 on 2022-09-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderplaced_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentDealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessdeal_data', to='store.businessdeal')),
            ],
        ),
    ]
