# Generated by Django 4.1 on 2022-10-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_web_dynamic_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Web_Dynamic_Content',
            new_name='WebDynamicContent',
        ),
    ]
