# Generated by Django 4.1 on 2022-10-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_businessdeal_condition_differentdealdata_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdeal',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
