# Generated by Django 4.1 on 2022-10-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_businessdeal_deal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bannermedia',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
