# Generated by Django 4.1 on 2022-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_banner_is_deleted_alter_bannermedia_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdeal',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
