# Generated by Django 4.1 on 2022-10-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_user_dial_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
