# Generated by Django 4.1 on 2022-10-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_businessdeal_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstore',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
