# Generated by Django 4.1 on 2022-10-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_differentdealdata_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_officer',
            name='business_store',
        ),
        migrations.AddField(
            model_name='account_officer',
            name='business_store',
            field=models.ManyToManyField(blank=True, null=True, to='store.businessstore'),
        ),
    ]
