# Generated by Django 4.1 on 2022-10-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='option_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='store_cart_items', to='store.differentdealdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='orignal_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
