# Generated by Django 4.1 on 2022-10-24 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_cartitem_option_id_cartitem_orignal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_cart_items', to='store.businessdeal'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='option_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_cart_items', to='store.differentdealdata'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_cart_items', to='store.businessstore'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
