# Generated by Django 4.1 on 2022-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_businessstore_total_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentdealdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
