# Generated by Django 4.1 on 2022-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_differentdealdata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdynamiccontent',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webdynamiccontent',
            name='contact_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webdynamiccontent',
            name='faq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webdynamiccontent',
            name='privacy_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webdynamiccontent',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
