# Generated by Django 4.1 on 2022-10-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_account_officer_business_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstore',
            name='is_account_officer',
            field=models.BooleanField(default=False),
        ),
    ]
