# Generated by Django 4.1 on 2022-10-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_businessdeal_latitude_businessdeal_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdeal',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessdeal',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessstore',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessstore',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='businessstore',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='businessstore',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='store.subcategory'),
        ),
    ]
