# Generated by Django 4.1 on 2022-11-01 06:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_businessdeal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='reservation_fee',
            field=models.PositiveIntegerField(default=20, verbose_name='Reservation Fee in Dirham'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Stripe', 'Stripe'), ('Paypal', 'Paypal')], default='Cash', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount', models.IntegerField(default=0, verbose_name='Current Discount in Percentage')),
                ('deal_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_option_orders', to='store.differentdealdata')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.orderplaced')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCardCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('card_number', models.CharField(default='', max_length=24)),
                ('card_holder', models.CharField(default='', max_length=100)),
                ('expire_at', models.DateField()),
                ('cvv', models.CharField(default='', max_length=5)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_checkout', to='store.orderplaced')),
            ],
        ),
    ]
