# Generated by Django 4.1 on 2022-11-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_orderplaced_reservation_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdeal',
            name='location',
        ),
        migrations.AddField(
            model_name='businessdeal',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='store.storelocation'),
        ),
    ]
