# Generated by Django 4.1 on 2022-11-01 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_businessdeal_location_businessdeal_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercardcheckout',
            options={'verbose_name': 'Order Bank Card Checkout Detail', 'verbose_name_plural': 'Order Bank Card Checkout Details'},
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='delivery_charges',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='store',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders_placed', to=settings.AUTH_USER_MODEL),
        ),
    ]
