# Generated by Django 4.1 on 2022-11-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_orderplaced_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/qr_code_images/'),
        ),
    ]
