# Generated by Django 4.1 on 2022-11-01 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_orderplaced_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
