# Generated by Django 4.1 on 2022-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_exceptionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='random_images/')),
            ],
        ),
    ]
