# Generated by Django 4.1 on 2022-11-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_randomfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=30, null=True),
        ),
    ]
