# Generated by Django 4.1 on 2022-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_storelocation_lat_storelocation_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstore',
            name='store_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=50),
        ),
    ]
