# Generated by Django 4.1 on 2022-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_businessstore_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdeal',
            name='location',
            field=models.ManyToManyField(blank=True, default='', null=True, to='store.storelocation'),
        ),
    ]
