# Generated by Django 4.1 on 2022-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_alter_businessdeal_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdeal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdeal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
