# Generated by Django 4.1 on 2022-11-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_businessdeal_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
