# Generated by Django 3.2.16 on 2022-11-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_storelocation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentdealdata',
            name='no_seats',
            field=models.IntegerField(default=0, verbose_name='No of seats'),
        ),
        migrations.AddField(
            model_name='differentdealdata',
            name='no_seats_booked',
            field=models.IntegerField(default=0, verbose_name='No of seats booked '),
        ),
    ]
