# Generated by Django 4.1 on 2022-11-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_auto_20221110_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdeal',
            name='is_continue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='differentdealdata',
            name='reservation_fee',
            field=models.IntegerField(default=0),
        ),
    ]
