# Generated by Django 4.1 on 2022-11-11 12:13

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_orderitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercardcheckout',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
