# Generated by Django 4.1 on 2022-11-11 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_ordercardcheckout_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subcategory', to='store.subcategory'),
        ),
    ]
