# Generated by Django 4.1 on 2022-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_user_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.TextField(blank=True, null=True)),
                ('faq_answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='terms_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
