# Generated by Django 4.1 on 2022-11-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_faq_user_terms_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('business_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deallocation_deal', to='store.businessdeal')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deallocation_locations', to='store.storelocation')),
            ],
        ),
    ]
