# Generated by Django 4.1 on 2022-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_deallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstore',
            name='commission_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessstore',
            name='reservation_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
